package de.ronny_h.aoc.year2017.day15

import de.infix.testBalloon.framework.core.TestConfig
import de.infix.testBalloon.framework.core.TestConfig.Invocation.Sequential
import de.infix.testBalloon.framework.core.invocation
import de.infix.testBalloon.framework.core.testSuite
import io.kotest.matchers.shouldBe

val DuelingGeneratorsTest by testSuite {

    testSuite(
        "generators A and B",
        testConfig = TestConfig.invocation(Sequential),
    ) {
        testFixture {
            object {
                val generatorA = Generator(65, 16807)
                val generatorB = Generator(8921, 48271)
            }
        } asContextForAll {
            mapOf(
                1092455 to 430625591,
                1181022009 to 1233683848,
                245556042 to 1431495498,
                1744312007 to 137874439,
                1352636452 to 285222916,
            ).forEach { (a, b) ->
                test("$a, $b") {
                    generatorA.next() shouldBe a
                    generatorB.next() shouldBe b
                }
            }
        }
    }

    test("part 1: The number of equal lowest 16 bit values in a sample of 40 million pairs") {
        val input = listOf(
            "Generator A starts with 65",
            "Generator B starts with 8921",
        )
        DuelingGenerators().part1(input) shouldBe 588
    }

    testSuite(
        "generators A and B only providing multiples",
        testConfig = TestConfig.invocation(Sequential),
    ) {
        testFixture {
            object {
                val generatorA = Generator(65, 16807, 4)
                val generatorB = Generator(8921, 48271, 8)
            }
        } asContextForAll {
            mapOf(
                1352636452 to 1233683848,
                1992081072 to 862516352,
                530830436 to 1159784568,
                1980017072 to 1616057672,
                740335192 to 412269392,
            ).forEach { (a, b) ->
                test("$a, $b") {
                    generatorA.next() shouldBe a
                    generatorB.next() shouldBe b
                }
            }
        }
    }

    test("part 2: The number of equal lowest 16 bit values generated by modified generators in a sample of 5 million pairs") {
        val input = listOf(
            "Generator A starts with 65",
            "Generator B starts with 8921",
        )
        DuelingGenerators().part2(input) shouldBe 309
    }
}
