package de.ronny_h.aoc.year2025.day07

import de.ronny_h.aoc.extensions.asList
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class LaboratoriesTest : StringSpec({

    val input = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
    """.asList()

    "part 1" {
        Laboratories().part1(input) shouldBe 21
    }

    "part 2" {
        Laboratories().part2(input) shouldBe 40
    }
})
