package de.ronny_h.aoc.year2025.day07

import de.infix.testBalloon.framework.core.testSuite
import de.ronny_h.aoc.extensions.asList
import io.kotest.matchers.shouldBe

val LaboratoriesTest by testSuite {

    val input = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
    """.asList()

    test("part 1") {
        Laboratories().part1(input) shouldBe 21
    }

    test("part 2") {
        Laboratories().part2(input) shouldBe 40
    }
}
